/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReposRouteRouteImport } from './routes/repos/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposIndexRouteImport } from './routes/repos/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ReposOwnerRepoRouteImport } from './routes/repos/$owner/$repo'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ReposRouteRoute = ReposRouteRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIndexRoute = ReposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReposRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerRepoRoute = ReposOwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => ReposRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repos': typeof ReposRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/repos/': typeof ReposIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/repos': typeof ReposIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repos': typeof ReposRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/repos/': typeof ReposIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/repos'
    | '/login'
    | '/repos/'
    | '/api/auth/$'
    | '/repos/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/repos' | '/api/auth/$' | '/repos/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/repos'
    | '/login/'
    | '/repos/'
    | '/api/auth/$'
    | '/repos/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReposRouteRoute: typeof ReposRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/': {
      id: '/repos/'
      path: '/'
      fullPath: '/repos/'
      preLoaderRoute: typeof ReposIndexRouteImport
      parentRoute: typeof ReposRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$repo': {
      id: '/repos/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/repos/$owner/$repo'
      preLoaderRoute: typeof ReposOwnerRepoRouteImport
      parentRoute: typeof ReposRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReposRouteRouteChildren {
  ReposIndexRoute: typeof ReposIndexRoute
  ReposOwnerRepoRoute: typeof ReposOwnerRepoRoute
}

const ReposRouteRouteChildren: ReposRouteRouteChildren = {
  ReposIndexRoute: ReposIndexRoute,
  ReposOwnerRepoRoute: ReposOwnerRepoRoute,
}

const ReposRouteRouteWithChildren = ReposRouteRoute._addFileChildren(
  ReposRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReposRouteRoute: ReposRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
